using System.Text.Json;
using LifeOverYears.Services.Interfaces;
using Microsoft.Extensions.Logging;

namespace LifeOverYears.Providers;

// The provider currently delivers nothing: it records job state and the
// pipeline waits on the run folder — era images arrive in images/ from
// outside (generated by hand from the prompts). OpenAiImageProvider will
// later implement real submit/download with the same contract.
public sealed class StubImageProvider : IImageGenerationProvider
{
    private static readonly JsonSerializerOptions JobJson =
        new(JsonSerializerDefaults.Web) { WriteIndented = true };

    private readonly ILogger<StubImageProvider> _logger;

    public StubImageProvider(ILogger<StubImageProvider> logger)
    {
        _logger = logger;
    }

    public async Task SynthesizeBaseAsync(string prompt, string outputPath)
    {
        // Nothing to copy from — there is no source photo in synthetic mode, so
        // the base has to come from outside like the era images do.
        _logger.LogWarning(
            "[Stub] SynthesizeBase: no image written — generate the base from prompts/base_synthetic.txt and place it at {Output}",
            outputPath);
        await Task.CompletedTask;
    }

    public async Task CleanBaseAsync(string sourcePath, string prompt, string outputPath)
    {
        File.Copy(sourcePath, outputPath, overwrite: true);
        _logger.LogInformation("[Stub] CleanBase: copied source to {Output} (prompt {Length} chars)",
            outputPath, prompt.Length);
        await Task.CompletedTask;
    }

    public async Task SubmitEraAsync(
        string basePath, string prompt, int year, string jobsDir,
        string? referenceImagePath = null)
    {
        Directory.CreateDirectory(jobsDir);
        var job = new
        {
            year,
            provider    = "stub",
            jobId       = $"stub-{year}",
            // Recorded rather than ignored: the images are generated by hand
            // from the prompt in this mode, and the reference is the second file
            // whoever does that has to open.
            reference   = referenceImagePath,
            submittedAt = DateTimeOffset.UtcNow.ToString("o")
        };
        await File.WriteAllTextAsync(
            Path.Combine(jobsDir, $"{year}.json"),
            JsonSerializer.Serialize(job, JobJson));
        _logger.LogInformation(
            "Job {Year} submitted — generate the image from prompts/{Year}.txt{Reference} and place it at images/{Year}.png",
            year, year,
            referenceImagePath is null ? "" : $" with reference {referenceImagePath}",
            year);
    }

    public Task<bool> TryCollectAsync(string jobsDir, int year, string outputPath)
    {
        var jobPath = Path.Combine(jobsDir, $"{year}.json");
        if (!File.Exists(jobPath))
            throw new InvalidOperationException(
                $"No job state for year {year} in {jobsDir} — was this year ever submitted?");

        return Task.FromResult(false);
    }
}
