using System.Text.Json;
using LifeOverYears.Services.Interfaces;
using Microsoft.Extensions.Logging;

namespace LifeOverYears.Providers;

// The provider currently delivers nothing: it records job state and the
// pipeline waits on the run folder — era images arrive in images/ from
// outside (generated by hand from the prompts). OpenAiImageProvider will
// later implement real submit/download with the same contract.
public sealed class StubImageProvider : IImageGenerationProvider
{
    private static readonly JsonSerializerOptions JobJson =
        new(JsonSerializerDefaults.Web) { WriteIndented = true };

    private readonly ILogger<StubImageProvider> _logger;

    public StubImageProvider(ILogger<StubImageProvider> logger)
    {
        _logger = logger;
    }

    public async Task CleanBaseAsync(string sourcePath, string prompt, string outputPath)
    {
        File.Copy(sourcePath, outputPath, overwrite: true);
        _logger.LogInformation("[Stub] CleanBase: copied source to {Output} (prompt {Length} chars)",
            outputPath, prompt.Length);
        await Task.CompletedTask;
    }

    public async Task SubmitEraAsync(string basePath, string prompt, int year, string jobsDir)
    {
        Directory.CreateDirectory(jobsDir);
        var job = new
        {
            year,
            provider    = "stub",
            jobId       = $"stub-{year}",
            submittedAt = DateTimeOffset.UtcNow.ToString("o")
        };
        await File.WriteAllTextAsync(
            Path.Combine(jobsDir, $"{year}.json"),
            JsonSerializer.Serialize(job, JobJson));
        _logger.LogInformation(
            "Job {Year} submitted — generate the image from prompts/{Year}.txt and place it at images/{Year}.png",
            year, year, year);
    }

    public Task<bool> TryCollectAsync(string jobsDir, int year, string outputPath)
    {
        var jobPath = Path.Combine(jobsDir, $"{year}.json");
        if (!File.Exists(jobPath))
            throw new InvalidOperationException(
                $"No job state for year {year} in {jobsDir} — was this year ever submitted?");

        return Task.FromResult(false);
    }
}
